services:
  postgres:
    image: postgres:16
    container_name: postgres_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  # MailDev - SMTP server for development (captures emails)
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080" # Web interface
      - "1025:1025" # SMTP port
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak_dev
    command: start-dev --import-realm --db=postgres
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    volumes:
      - ./keycloak-theme:/opt/keycloak/themes
      - ./myrealm-export.json:/opt/keycloak/data/import/myrealm.json
    depends_on:
      - postgres
      - maildev

volumes:
  postgres_data:
